spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  flyway:
    enabled: false
  mail:
    host: localhost
    port: 3025
    username: test
    password: test
    properties:
      mail.smtp.auth: false
      mail.smtp.starttls.enable: false

app:
  jwt-secret: 404E635266556A586E3272357538782F413F4428472B4B6250655368566D5970
  jwt-expiration-ms: 3600000
  frontend-url: http://localhost:8081
